on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs: 
      version: ${{ steps.set-version.outputs.version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set VERSION variable from tag
      id: set-version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Show VERSION
      run: echo ${{ env.version }}
